// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AichatMessage
{
    public string AichatMessageId { get; set; }

    public string AichatMessageSenderType { get; set; }

    public DateTime? AichatMessageSentAt { get; set; }

    public string AichatMessageContent { get; set; }

    public string AichatSessionId { get; set; }

    public virtual AichatSession AichatSession { get; set; }
}