// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AichatSession
{
    public string AichatSessionId { get; set; }

    public string AichatSessionTitle { get; set; }

    public DateTime? AichatSessionCreatedAt { get; set; }

    public string ProfileId { get; set; }

    public virtual ICollection<AichatMessage> AichatMessages { get; set; } = new List<AichatMessage>();

    public virtual Profile Profile { get; set; }
}