// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Article
{
    public string ArticleId { get; set; }

    public string ArticleName { get; set; }

    public string ArticleUrl { get; set; }

    public string ArticleDescription { get; set; }

    public string ArticleContent { get; set; }
}