// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Audio
{
    public string AudioId { get; set; }

    public string AudioTitle { get; set; }

    public string AudioUrl { get; set; }

    public string AudioThumbnail { get; set; }

    public DateTime? AudioCreatedAt { get; set; }

    public bool? AudioIsPremium { get; set; }

    public string AudioStatus { get; set; }

    public string SubAudioCategoryId { get; set; }

    public virtual SubAudioCategory SubAudioCategory { get; set; }
}