// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class AudioCategory
{
    public string AudioCategoryId { get; set; }

    public string AudioCategoryName { get; set; }

    public virtual ICollection<SubAudioCategory> SubAudioCategories { get; set; } = new List<SubAudioCategory>();
}