// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class CommunityMember
{
    public string CommunityMemberId { get; set; }

    public string CommunityMemberStatus { get; set; }

    public string CommunityGroupId { get; set; }

    public string ProfileId { get; set; }

    public virtual UserCommunity CommunityGroup { get; set; }

    public virtual Profile Profile { get; set; }
}