// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class CommunityPost
{
    public string CommunityPostId { get; set; }

    public string CommunityPostTitle { get; set; }

    public string CommunityPostContent { get; set; }

    public string CommunityPostImageUrl { get; set; }

    public string CommunityPostStatus { get; set; }

    public DateTime? CommunityPostCreatedAt { get; set; }

    public string CommunityGroupId { get; set; }

    public string ProfileId { get; set; }

    public virtual UserCommunity CommunityGroup { get; set; }

    public virtual Profile Profile { get; set; }
}