// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Goal
{
    public string GoalId { get; set; }

    public string GoalTitle { get; set; }

    public string GoalDescription { get; set; }

    public string GoalType { get; set; }

    public DateTime? GoalStartDate { get; set; }

    public DateTime? GoalEndDate { get; set; }

    public int? GoalTargetCount { get; set; }

    public int? GoalPeriodDays { get; set; }

    public string GoalStatus { get; set; }

    public DateTime? GoalCreatedAt { get; set; }

    public DateTime? GoalUpdatedAt { get; set; }

    public DateTime? GoalCompletedAt { get; set; }

    public string ProfileId { get; set; }

    public virtual Profile Profile { get; set; }
}