// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Habit
{
    public string HabitId { get; set; }

    public string HabitName { get; set; }

    public string HabitDescription { get; set; }

    public string ProfileId { get; set; }

    public virtual Profile Profile { get; set; }
}