// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class HelpCategory
{
    public string HelpCategoryId { get; set; }

    public string HelpCategoryName { get; set; }

    public virtual ICollection<Help> Helps { get; set; } = new List<Help>();
}