// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Help
{
    public string HelpId { get; set; }

    public string HelpAnswer { get; set; }

    public string HelpQuestion { get; set; }

    public DateTime? HelpCreatedAt { get; set; }

    public string HelpCategoryId { get; set; }

    public virtual HelpCategory HelpCategory { get; set; }
}