// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MoodJournal
{
    public string MoodJournalId { get; set; }

    public string MoodJournalTitle { get; set; }

    public string MoodJournalEmotion { get; set; }

    public string MoodJournalDescription { get; set; }

    public DateTime? MoodJournalCreatedAt { get; set; }

    public string MoodJournalTypeId { get; set; }

    public string ProfileId { get; set; }

    public virtual MoodJournalType MoodJournalType { get; set; }

    public virtual Profile Profile { get; set; }
}