// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class MoodJournalType
{
    public string MoodJournalTypeId { get; set; }

    public string MoodJournalTypeName { get; set; }

    public virtual ICollection<MoodJournal> MoodJournals { get; set; } = new List<MoodJournal>();
}