// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Notification
{
    public string NotificationId { get; set; }

    public string NotificationUrl { get; set; }

    public string NotificationName { get; set; }

    public string NotificationDescription { get; set; }

    public string UserId { get; set; }

    public virtual User User { get; set; }
}