// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Profile
{
    public string ProfileId { get; set; }

    public string UserId { get; set; }

    public string ProfileName { get; set; }

    public string ProfileStatus { get; set; }

    public virtual ICollection<AichatSession> AichatSessions { get; set; } = new List<AichatSession>();

    public virtual ICollection<CommunityMember> CommunityMembers { get; set; } = new List<CommunityMember>();

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();

    public virtual ICollection<Goal> Goals { get; set; } = new List<Goal>();

    public virtual ICollection<Habit> Habits { get; set; } = new List<Habit>();

    public virtual ICollection<MoodJournal> MoodJournals { get; set; } = new List<MoodJournal>();

    public virtual ICollection<QuizUserAnswer> QuizUserAnswers { get; set; } = new List<QuizUserAnswer>();

    public virtual ICollection<QuizUserAttempt> QuizUserAttempts { get; set; } = new List<QuizUserAttempt>();

    public virtual ICollection<QuizUserResult> QuizUserResults { get; set; } = new List<QuizUserResult>();

    public virtual ICollection<RefreshToken> RefreshTokens { get; set; } = new List<RefreshToken>();

    public virtual ICollection<Session> Sessions { get; set; } = new List<Session>();

    public virtual User User { get; set; }
}