// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Quiz
{
    public string QuizId { get; set; }

    public string QuizTitle { get; set; }

    public string QuizDescription { get; set; }

    public DateTime? QuizCreatedAt { get; set; }

    public DateTime? QuizUpdatedAt { get; set; }

    public string QuizStatus { get; set; }

    public double? QuizMaxScore { get; set; }

    public string QuizCategoryId { get; set; }

    public virtual QuizCategory QuizCategory { get; set; }

    public virtual ICollection<QuizQuestion> QuizQuestions { get; set; } = new List<QuizQuestion>();

    public virtual ICollection<QuizUserAnswer> QuizUserAnswers { get; set; } = new List<QuizUserAnswer>();

    public virtual ICollection<QuizUserAttempt> QuizUserAttempts { get; set; } = new List<QuizUserAttempt>();

    public virtual ICollection<QuizUserResult> QuizUserResults { get; set; } = new List<QuizUserResult>();
}