// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class QuizQuestion
{
    public string QuizQuestionId { get; set; }

    public string QuizQuestionContent { get; set; }

    public int? QuizQuestionOrder { get; set; }

    public string QuizId { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<QuizAnswerOption> QuizAnswerOptions { get; set; } = new List<QuizAnswerOption>();

    public virtual ICollection<QuizUserAnswer> QuizUserAnswers { get; set; } = new List<QuizUserAnswer>();
}