// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class QuizUserAttempt
{
    public string QuizUserAttemptId { get; set; }

    public DateTime? QuizUserAnswerCreatedAt { get; set; }

    public string ProfileId { get; set; }

    public string QuizId { get; set; }

    public virtual Profile Profile { get; set; }

    public virtual Quiz Quiz { get; set; }

    public virtual ICollection<QuizUserAnswer> QuizUserAnswers { get; set; } = new List<QuizUserAnswer>();

    public virtual ICollection<QuizUserResult> QuizUserResults { get; set; } = new List<QuizUserResult>();
}