// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class RefreshToken
{
    public string RefreshTokenId { get; set; }

    public string Token { get; set; }

    public string ProfileId { get; set; }

    public string UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? ExpiresAt { get; set; }

    public bool? IsRevoked { get; set; }

    public virtual Profile Profile { get; set; }

    public virtual User User { get; set; }
}