// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Session
{
    public string SessionId { get; set; }

    public string UserId { get; set; }

    public string ProfileId { get; set; }

    public string Token { get; set; }

    public bool? SessionIsActive { get; set; }

    public virtual Profile Profile { get; set; }

    public virtual User User { get; set; }
}