// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class SubAudioCategory
{
    public string SubAudioCategoryId { get; set; }

    public string SubAudioCategoryName { get; set; }

    public string AudioCategoryId { get; set; }

    public virtual AudioCategory AudioCategory { get; set; }

    public virtual ICollection<Audio> Audios { get; set; } = new List<Audio>();
}