// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class Subscription
{
    public string SubscriptionId { get; set; }

    public string SubscriptionType { get; set; }

    public string SubscriptionDescription { get; set; }

    public double? SubscriptionPrice { get; set; }

    public virtual ICollection<Purchase> Purchases { get; set; } = new List<Purchase>();
}