// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Repository.Models;

public partial class UserCommunity
{
    public string CommunityGroupId { get; set; }

    public string CommunityName { get; set; }

    public string CommunityDescription { get; set; }

    public DateTime? CommunityCreatedAt { get; set; }

    public string CommunityStatus { get; set; }

    public virtual ICollection<CommunityMember> CommunityMembers { get; set; } = new List<CommunityMember>();

    public virtual ICollection<CommunityPost> CommunityPosts { get; set; } = new List<CommunityPost>();
}